import Head from "next/head";
import Gallery from "./gallery";
import data from "@/data/imageData";
import { useState } from "react";
import Pagination from "@/components/pagination";

export default function Home() {
  const [imagesData, setImagesData] = useState(data);
  const [searchValue, setSearchValue] = useState("");
  const [page, setPage] = useState(1);
  const filterdArray = imagesData.filter((currItem) =>
    currItem.description.includes(searchValue)
  );

  console.log(filterdArray);

  return (
    <div>
      <Head>
        <title>Next Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/*  search functionality starts */}
        <div className="w-full flex justify-center mt-10">
          <input
            placeholder="search images 🔍 "
            className="p-2 bg-gray-200  text-center"
            value={searchValue}
            onChange={(e) => setSearchValue(e.target.value)}
          />
        </div>
        {/*  search functionality ends */}

        <div className=" mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
          <div className=" ml-11 grid grid-cols-1 gap-y-10 gap-x-6  sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 xl:gap-x-8">
            {filterdArray.slice(page * 20 - 20, page * 20).map((elem) => (
              <Gallery
                imageUrl={elem.imageUrl}
                description={elem.description}
                id={elem.id}
              />
            ))}
          </div>
        </div>
        <Pagination page={page} setPage={setPage} totalImages={filterdArray} />
      </main>
    </div>
  );
}
